---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Ensure Nginx is started and enabled
  service:
    name: nginx
    state: started
    enabled: yes

- name: Configure Nginx as reverse proxy
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/reverse-proxy.conf

- name: Enable Nginx reverse proxy site
  file:
    src: /etc/nginx/sites-available/reverse-proxy.conf
    dest: /etc/nginx/sites-enabled/reverse-proxy.conf
    state: link
    force: yes

- name: Remove default Nginx site (optional)
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart Nginx to apply changes
  service:
    name: nginx
    state: restarted
